### ISSUE TITLE
Add node_exporter template

### ISSUE THREAD

**Issue by rvashishth** [apache/pulsar-helm-chart#103]
**Is your feature request related to a problem? Please describe.**
The grafana dashboards should display metrics for nodes and containers. Use prometheus `node_exporter` to export kubernetes node metrics.

**Describe the solution you'd like**
Define node exporter template as defined at [streamnative charts](https://github.com/streamnative/charts/blob/master/charts/pulsar/templates/node-exporter/node-exporter.yaml)

**Additional context**
Although [`monitoring.node_exporter`](https://github.com/apache/pulsar-helm-chart/blob/master/charts/pulsar/values.yaml#L125) is enabled at values.yml file but it seems no template for node_exporters are defined yet.

**Comment by mkoertgen** [comment]
Probably removed because most clusters will typically already have a similar daemonset?

As a workaround can we just deploy a standard node-exporter?
- https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-node-exporter

**Comment by mkoertgen** [comment]
Added as mentioned above with podAnnotations scrape: true

**Comment by lhotari** [comment]
Since 3.0.0 chart version, kube-prometheus-stack has been used for Prometheus and Grafana. Closing this issue.
