### ISSUE TITLE
bookkeeper-statefulset.yaml has indentation issue in volumeMounts array

### ISSUE THREAD

**Issue by sunswei** [apache/pulsar-helm-chart#106]
**Describe the bug**
         volumeMounts:
         {{- if .Values.bookkeeper.volumes.useSingleCommonVolume }}
-          - name: "{{ template "pulsar.fullname" . }}-{{ .Values.bookkeeper.component }}-{{ .Values.bookkeeper.volumes.common.name }}"
-            mountPath: /pulsar/data/bookkeeper
+        - name: "{{ template "pulsar.fullname" . }}-{{ .Values.bookkeeper.component }}-{{ .Values.bookkeeper.volumes.common.name }}"
+          mountPath: /pulsar/data/bookkeeper

**To Reproduce**
when setting the tls.zookeeper.enable to true, this issue makes "helm template YAML to JSON error" 

**Expected behavior**

**Comment by lhotari** [comment]
Fixed by #384
