### ISSUE TITLE
Pulsar manager always uses default user/password

### ISSUE THREAD

**Issue by sloan-dog** [apache/pulsar-helm-chart#108]
#### Expected behavior
Providing non default username and password for Pulsar Admin Manager component should actually change the username and password

#### Actual behavior
Pulsar admin manager always uses the default username and password (not secure)

#### Steps to reproduce
`helm upgrade --install --set pulsar_manager.admin.password=myspecialpassword --set pulsar_manager.admin.user=myspecialuser --set initialize=true --values examples/values-minikube.yaml --namespace pulsar pulsar-mini apache/pulsar`

*I am aware that default chart does not restart pods if the secret changes, but lets say this is fresh install (also the case). 

#### System configuration
**Helm chart commit**: c059ea25d80d6165b67ee163252a682198d8933f

Using all default values for minkube

**Comment by jeantil** [comment]
hi @sloan-dog , this report looks a lot like #31 to me :)

**Comment by lhotari** [comment]
Please review PR #212, it should fix this issue.

**Comment by mkoertgen** [comment]
Hi @lhotari ,

As a workaround, I managed to create a simple k8s-job that performed the steps described in
- https://pulsar.apache.org/docs/en/administration-pulsar-manager/#set-administrator-account-and-password

Here is the gist of it:
- https://gist.github.com/mkoertgen/a3c45689e78b88f71d2c373a243c95d7

Please have a look. It should be straight-forward to add it to the helm chart as a [post-install helm-hook](https://helm.sh/docs/topics/charts_hooks/)

**Note:** Not sure whether the pod also needs to persist state. Might be the configuration gets lots on restarts (not sure where this is persisted).

**Comment by lhotari** [comment]
solved by #457
