### ISSUE TITLE
Use hooks instead of initialize=true

### ISSUE THREAD

**Issue by Laurianti** [apache/pulsar-helm-chart#114]
Why don't use pre-install or post-install hooks?
Any reason?

https://helm.sh/docs/topics/charts_hooks/
![115307963-4d467300-a16a-11eb-83c3-8138ad2aaac2](https://user-images.githubusercontent.com/20415513/115384963-e8c1fd00-a1d7-11eb-900e-39e2a6807bbf.png)
![115307997-5b948f00-a16a-11eb-8e33-e29da243fd17](https://user-images.githubusercontent.com/20415513/115384979-eb245700-a1d7-11eb-8afc-157238b35f92.png)

https://github.com/apache/pulsar-helm-chart/pull/53

**Comment by lhotari** [comment]
Another solution proposed by @mkoertgen  https://github.com/apache/pulsar-helm-chart/issues/124#issuecomment-1004724440

**Comment by lhotari** [comment]
There's already a PR #138 for resolving this.
