### ISSUE TITLE
pulsar deploy in k8s  zookeeper error

### ISSUE THREAD

**Issue by klaus-pd** [apache/pulsar-helm-chart#120]
**Describe the bug**
The Pulsar2.7.1 cluster was deployed on K8S using the officially provided Helm cluster, but the ZooKeeper cluster deployment could not complete the initialization of the cluster. Due to a problem with ZooKeeper, Pulsar-Proxy, Pulsar-Broker, Pulsar-Bookie, and Pulsar-Recovery are all processing the wait state and cannot be started

<img width="1583" alt="image" src="https://user-images.githubusercontent.com/9957221/118625702-d1892600-b7fc-11eb-9880-97511025c7ff.png">

**Comment by lhotari** [comment]
Outdated issue. Possible solution could be to add `--set affinity.anti_affinity=false` if this is a single node deployment. Please retry with up-to-date versions.
