### ISSUE TITLE
Change to PULSAR_GC in values.yaml -XX args for Pulsar 2.8.0 needed

### ISSUE THREAD

**Issue by andrekramer1** [apache/pulsar-helm-chart#134]
**Describe the bug**
When using Pulsar 2.8.0 (recently released) with the helm chart which is currently at 2.7.2 bookie pods fail to initialize as the init commands java command (to run bookkeeper shell) fails because of invalid command line arguments for the GC configuration.

**To Reproduce**
Change image to 2.8.0 (we were using a private build but problem would still apply to public image) and create or update a cluster. Bookies fail to init.

**Expected behavior**
Bookies to init after the java bookkeeper shell get instance id initialization.

**Additional context**
A simple fix is to modify the PULSAR_GC environment variable by changing the charts/pulsar/values.yaml file to be:

 PULSAR_GC: >
      -XX:+UseG1GC
      -XX:MaxGCPauseMillis=10
      -XX:+ParallelRefProcEnabled
      -XX:+UnlockExperimentalVMOptions
      -XX:+DoEscapeAnalysis
      -XX:ParallelGCThreads=4
      -XX:ConcGCThreads=4
      -XX:G1NewSizePercent=50
      -XX:+DisableExplicitGC
      -XX:-ResizePLAB
      -XX:+ExitOnOutOfMemoryError
      -XX:+PerfDisableSharedMem
      -XX:+PrintGCDetails
      -verbosegc
      -Xloggc:/var/log/bookie-gc.log

(Removing 4 -XX/-X args)

Current values.yaml:

 PULSAR_GC: >
      -XX:+UseG1GC
      -XX:MaxGCPauseMillis=10
      -XX:+ParallelRefProcEnabled
      -XX:+UnlockExperimentalVMOptions
      -XX:+DoEscapeAnalysis
      -XX:ParallelGCThreads=4
      -XX:ConcGCThreads=4
      -XX:G1NewSizePercent=50
      -XX:+DisableExplicitGC
      -XX:-ResizePLAB
      -XX:+ExitOnOutOfMemoryError
      -XX:+PerfDisableSharedMem
      -XX:+PrintGCDetails
      -XX:+PrintGCTimeStamps
      -XX:+PrintGCApplicationStoppedTime
      -XX:+PrintHeapAtGC
      -verbosegc
      -Xloggc:/var/log/bookie-gc.log
      -XX:G1LogLevel=finest

**Comment by eolivelli** [comment]
Are you interested in sending a patch?

**Comment by andrekramer1** [comment]
Probably should be done as part of upgrade to 2.8.0. Leaving as is for 2.7.x.

**Comment by Lanayx** [comment]
I can confirm that bookie 2.8.0 won't start without this change.

**Comment by lhotari** [comment]
This is handled as part of #190
