### ISSUE TITLE
upload schemas error http 500

### ISSUE THREAD

**Issue by iTigeroar** [apache/pulsar-helm-chart#136]
Expected behavior
upload schema success

Actual behavior
deploy pulsar by helm apache/pulsar
root@pulsar-toolset-0:/pulsar# ./bin/pulsar-admin topics create persistent://public/default/postgres-sink-topic
root@pulsar-toolset-0:/pulsar# ./bin/pulsar-admin schemas upload persistent://public/default/postgres-sink-topic -f ./connectors/avro-schema
[AsyncHttpClient07-1] WARN org.apache.pulsar.client.admin.internal.BaseResource - [http://pulsar-proxy:443/admin/v2/schemas/public/default/postgres-sink-topic/schema] Failed to perform http post request: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error HTTP 300 Internal Server Error

Reason: HTTP 500 Internal Server Errorjava.io.ByteArrayInputStream@5369986

Steps to reproduce
How can we reproduce the issue

System configuration
Pulsar version: 2.7.2

**Comment by liangyuanpeng** [comment]
I believe thath you should create this issue to apache/pulsar.
