### ISSUE TITLE
The latest chart 2.7.2 does not include the commits

### ISSUE THREAD

**Issue by longkai** [apache/pulsar-helm-chart#146]
I see the release contains the [commits](https://github.com/apache/pulsar-helm-chart/compare/pulsar-2.7.2...master#diff-cad39e6dbd3f1cdb2f7aecf8cfd26e3b9a5b31e7d79b3b8f175ccf6cfca2ad6a) which set the rbac from v1beta1 to v1.

However, if you install with helm or just download the tarball you can still see v1beta1.

This would fail on k8s 1.22 since it remove the old api.

**Comment by lhotari** [comment]
obsolete
