### ISSUE TITLE
Pulsar operator implmentation consideration 

### ISSUE THREAD

**Issue by rayliu419** [apache/pulsar-helm-chart#151]
Hi guys, 

I am a new operator developer and I know operator has three ways to implement. As far as I know, helm operator has limited functionalities compared with other methods, so I am curious why you choose helm to implment the puslar operator. 
From some sources, Helm operator only support basic install and rolling update( I guess this operator support these functionalities), but pulsar as a whole seems a complex application which needs more functionalities in  the future. 
Could you enlighten me the considerations when you adopt helm opeator? 

Thanks,

**Comment by lhotari** [comment]
Please discuss this on Pulsar Slack or GitHub Discussions, see https://pulsar.apache.org/community/#section-discussions
