### ISSUE TITLE
Pulsar manager default environment

### ISSUE THREAD

**Issue by acesir** [apache/pulsar-helm-chart#153]
Looking at this PR https://github.com/apache/pulsar-manager/pull/242 there is functionality which supports setting a default environment. I cannot seem to find any options for this in the existing helm chart. Is this functionality supported with the current release?

**Comment by liangyuanpeng** [comment]
I think you can use configmap of pulsar-manager to set your env.  

https://github.com/apache/pulsar-helm-chart/blob/master/charts/pulsar/templates/pulsar-manager-configmap.yaml  

https://github.com/apache/pulsar-helm-chart/blob/master/charts/pulsar/templates/pulsar-manager-deployment.yaml#L70

**Comment by acesir** [comment]
> I think you can use configmap of pulsar-manager to set your env.
> 
> https://github.com/apache/pulsar-helm-chart/blob/master/charts/pulsar/templates/pulsar-manager-configmap.yaml
> 
> https://github.com/apache/pulsar-helm-chart/blob/master/charts/pulsar/templates/pulsar-manager-deployment.yaml#L70

I have tried but using any variation of setting default_environment_name and service_url does not seem to propagate correctly. The application properties have the bellow config keys but there seems no way to set them and pass through so the environment is created. No docs around illustrating how to do it either.

```
# default environment configuration
default.environment.name=
default.environment.service_url=
```

**Comment by acesir** [comment]
We resorted to building our own image and modifying the init DB script as the current chart and docker image do not support this functionality.
