### ISSUE TITLE
Grafana data lost once pod restart.

### ISSUE THREAD

**Issue by dragonls** [apache/pulsar-helm-chart#154]
**Is your feature request related to a problem? Please describe.**
Now, pulsar-helm-chart use empty dir instead of pv. So once grafana pod restarts, the grafana data lost.

**Describe the solution you'd like**
Add grafana data persistence support.

**Comment by MarvinCai** [comment]
I think you mean loki and prometheus, I'll work on adding option to enable persistent storage for loki and prometheus.
