### ISSUE TITLE
Ingresses still use the extensions/v1beta1 versioned resource

### ISSUE THREAD

**Issue by dsonck92** [apache/pulsar-helm-chart#157]
**Describe the bug**
All the ingress templates still use the deprecated (since Kubernetes 1.19) extensions/v1beta1 Ingress instead of networking.k8s.io/v1 Ingress. In addition, support for this type will be dropped in the upcoming major Kubernetes version (1.22)

**To Reproduce**
1. Take the latest helm chart
2. Apply the helm chart with some ingresses turned on
3. Notice the warnings that extensions/v1beta1 Ingress is deprecated and support will be dropped in 1.22

**Expected behavior**
The chart should use the new networking.k8s.io/v1 Ingress.

**Comment by wangshu3000** [comment]
I'm working on this. 🥇
