### ISSUE TITLE
Function Worker - kubernetesContainerFactory

### ISSUE THREAD

**Issue by vitosans** [apache/pulsar-helm-chart#163]
**Describe the bug**
I managed to bring my pulsar cluster up using this helm chart and some modifications to enable mTLS authentication. 

This part is working and I plan to make a PR to help get this upstream. However, when I run pulsar functions with the kubernetesContainerFactory the config state is not inherited from the broker to the workers that get created via the kubernetesContainerFactory.  The following files are default and not configured: 

* certs/* 
* function_worker.yml 
* client.conf 

I see that a StatefulSet is created, and I can modify that to do some hackery, but I am wondering if I missed something or is this a bug in the way the functions workers are spawned when TLS is enabled. 

**To Reproduce**
1. enable TLS
2. modify broker, proxy, toolset, bookkeeper, zookeeper-configmap.yaml to include tls authentication bits 
3. Enable function worker
4. Deploy helm chart. 

**Expected behavior**
I would think that the function workers would inherit their config state from the brokers:  From the documentation:

In this mode, most of the settings are already inherited from your broker configuration (for example, configurationStore settings, authentication settings, and so on) since functions-worker is running as part of the broker.

Unless I have missed a step that I can't find any documentation on, I think this part is needed.

**Additional context**
I am using a fork from Master and my functions works do work correctly with no TLS and not authentication. Once I add authentication they do not work as they do not have any configs.

**Comment by lhotari** [comment]
#435 solves the problem. However there's no mTLS between Function worker and Broker. A new issue can be opened to cover that. Closing this issue.
