### ISSUE TITLE
2.7.3 helm chart still use 2.7.2 images

### ISSUE THREAD

**Issue by Maxzouz** [apache/pulsar-helm-chart#164]
**Describe the bug**
I've donwloaded the latest helm chart for pulsar (2.7.3). When opening the values.yaml file it still refers to 2.7.2 images

**To Reproduce**
Download the 2.7.3 chart
Open values.yaml

**Expected behavior**
Use of 2.7.3 images 

**Screenshots**
![image](https://user-images.githubusercontent.com/63256223/136372475-b8bf7571-d6c4-45e4-a59a-7656f088613f.png)

**Comment by javiramos1** [comment]
Hi, the chart is still using 2.7.2. I did change the tags to 2.8.1 but it did not work, the pods were stuck in init state.

**Comment by lhotari** [comment]
The helm chart version is independent from Pulsar's version. There's a separate PR #200 that would make image tag match the appVersion by default.
