### ISSUE TITLE
Pulsar minikube installation pods fail

### ISSUE THREAD

**Issue by pancudaniel7** [apache/pulsar-helm-chart#167]
**Describe the bug**
I've follow minikube pulsar installation for version v1.16.1 and after installing the the chart with minikube values I got pods freeze state.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://pulsar.apache.org/docs/en/2.7.1/kubernetes-helm/'
2. Follow exactly all the steps until the **helm install** step
3. Execute helm install and run kubectl get pods you will see fail state of the pods:

<img width="1179" alt="Screenshot 2021-10-25 at 22 30 20" src="https://user-images.githubusercontent.com/9675142/138758114-8975ce86-93b5-4905-9702-4e7a671720c4.png">

**Expected behaviour**
The pods state should be set to **Running**.

<img width="763" alt="Screenshot 2021-10-25 at 22 32 58" src="https://user-images.githubusercontent.com/9675142/138758508-cd2efccf-adb5-4d43-80f2-434a93f72e93.png">

**Desktop (please complete the following information):**
 - OS: Darwin MacBook-Pro 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

**Comment by michaeljmarshall** [comment]
@pancudaniel7 - can you provide a bit more context? When you describe the pods that are in a "freeze state", do they have any kubernetes events? Does it work eventually? Note that the docker images are large, so it can take a while to download them to your minikube docker daemon.

**Comment by lhotari** [comment]
Outdated issue. Please retry with latest version. `--set affinity.anti_affinity=false` is needed for single node k8s environments such as minikube.
