### ISSUE TITLE
Helm Chart installs Pulsar Manager V1.0

### ISSUE THREAD

**Issue by SapnaGirdhani1** [apache/pulsar-helm-chart#184]
I used Helm Chart to install Pulsar on my Kubernetes Cluster. It installs Pulsar 2.7.2 version (apachepulsar/pulsar-all:2.7.2) along with Pulsar Manager V1 ( apachepulsar/pulsar-manager:v0.1.0) by default. I want to have Pulsar manager V2. Not finding any way to configure Pulsar Manager V2.

**To Reproduce**
1. follow the link : https://pulsar.apache.org/docs/en/kubernetes-helm/  to configure Pulsar on Kubernetes Cluster. 
2. Check the available services.
3. It installs Pulsar Manager
4. Version is - apachepulsar/pulsar-manager:v0.1.0

**Expected behavior**
I need Pulsar manager V0.2.0 to work on HerdDB.There is no way I can specify the version.

**Desktop (please complete the following information):**
 - OS: IBM Cloud Kubernetes Cluster

**Additional context**
I need Pulsar Manager V0.2.0 version to work on HerdDB. Not able to capture jdbc url fromV0.1.0 version. 
So I am looking for a solution where I can:
1) Either install Pulsar and Pulsar manager separately
2) Or I can specify Pulsar Manager Version to be installed via Helm Chart

**Comment by michaeljmarshall** [comment]
@SapnaGirdhani1 - you can configure the version of the pulsar manager by adding the following to your helm values file: 

```yaml
pulsar_manager:
  tag: v0.2.0
```

Here are the default values for the current chart:

https://github.com/apache/pulsar-helm-chart/blob/cee3b5c5e6dd9edd1e7c584a941f076e5edf5a53/charts/pulsar/values.yaml#L190-L194

Please re-open your issue if my solution does not work. Thanks!
