### ISSUE TITLE
Github Actions should enforce an increase in helm chart semantic version on each PR

### ISSUE THREAD

**Issue by frankjkelly** [apache/pulsar-helm-chart#185]
**Is your feature request related to a problem? Please describe.**
The problem is each helm chart version is deployed once per version. See https://github.com/apache/pulsar-helm-chart/releases

So if someone makes an edit or improvement to the chart and we do not change the version then that change will not be seen until the next change where someone bumps the version and a new deployment is created.

**Describe the solution you'd like**
Seeking some kind of semantic version change check 

**Describe alternatives you've considered**
None I could think of

**Comment by michaeljmarshall** [comment]
I think a release for every change would lead to too many releases. However, there is an underlying problem that this issue points to: contributors to the helm chart feel that it can take too long to get a simple fix included in a release. As you mentioned, we use to only release the helm chart when Apache Pulsar was released. I'm not sure why we had the initial process, but I don't think we _need_ to synchronize releases of Pulsar and its official helm chart.

We could add something to the README or to a CONTRIBUTORS file that indicates how we version the chart and explicitly lets contributors know how to request a release. Note that anyone wanting to initiate a release can open a PR to bump the version of the helm chart.

**Comment by michaeljmarshall** [comment]
Thanks for your proposal @frankjkelly. Since we are updating the helm chart's release process, as proposed here #301, I am going to close this issue.
