### ISSUE TITLE
Unrecognized VM option 'PrintGCTimeStamps' - Unsupported Java 11 GC Flags causing init container fail

### ISSUE THREAD

**Issue by samzph** [apache/pulsar-helm-chart#188]
Need to update the PULSAR_GC options in the default values to remove flags or add `-XX:+IgnoreUnrecognizedVMOptions`, otherwise init containers fail. 

See here: https://confluence.atlassian.com/confkb/unrecognized-jvm-gc-options-when-using-java-11-1002472841.html

**Comment by lhotari** [comment]
@samuelzimmermanphillips Thanks for reporting. This will be fixed as part of #190.

**Comment by michaeljmarshall** [comment]
Fixed by #255
