### ISSUE TITLE
Zookeeper Pod Restarts frequently

### ISSUE THREAD

**Issue by shaileshjha061** [apache/pulsar-helm-chart#222]
**Zookeeper Pod Restarts frequently**
I tried Deploying Pulsar in GKE clusters using the helm chart. Pulsar cluster is being deployed properly but the zookeeper pods keep on restarting one by one. And also there is no error in logs that can be debugged.
**Pulsar Chart Version**:  pulsar-2.7.10

**To Reproduce the issue**
1. Create GKE Cluster
2. Create Namespace 
3. Add pulsar chart to your local Helm repository:
`helm repo add apache https://pulsar.apache.org/charts`
4. Install Chart using Helm cmd:
`helm install <release-name> apache/pulsar`

**Expected behavior**
We can see all Pulsar components pods are up and running. But the Zookeeper Pods will be restarting after 15-20 minutes.

**Screenshots**
![image](https://user-images.githubusercontent.com/62938663/151990038-ca415975-89ea-4085-9276-19fe1735c389.png)
Chart Version:
![image](https://user-images.githubusercontent.com/62938663/151990746-a68ae9b5-d2e5-4640-90ed-a84c316a3f9c.png)

**Comment by lhotari** [comment]
There's a promising fix in https://github.com/apache/pulsar/pull/14088 . I'm currently running an experiment in PR #190 with https://github.com/apache/pulsar-helm-chart/pull/190/commits/98dd0297f8782f2aa39dc1447ef6d0c4efbd6a5e .

**Comment by lhotari** [comment]
Is this issue fixed with chart version 2.7.11 ?

**Comment by shaileshjha061** [comment]
Yes. The Issue is Resolved. Thanks, @lhotari
