### ISSUE TITLE
broker's restartPodsOnConfigMapChange set to true, helm upgrade after broker exception

### ISSUE THREAD

**Issue by czhfe** [apache/pulsar-helm-chart#228]
broker's restartPodsOnConfigMapChange set to true, helm upgrade after broker exception

![image](https://user-images.githubusercontent.com/19341806/154045431-0be09518-e885-4beb-a30e-3b7f43451f20.png)

![image](https://user-images.githubusercontent.com/19341806/154045384-a6e0771f-2789-4df6-a144-ce9d58e7b680.png)

**Comment by michaeljmarshall** [comment]
@czhfe - what is the error you're observing?

**Comment by lhotari** [comment]
Closing this issue since there's no feedback from reporter.
