### ISSUE TITLE
Update pulsar-manager-service template to allow for admins to open multiple ports

### ISSUE THREAD

**Issue by bsheltonihs** [apache/pulsar-helm-chart#229]
**Is your feature request related to a problem? Please describe.**
I am using argo-cd to deploy on openshift using these helm charts. The issue I have is the backend admin service port is `7750` which the `pulsar-manager-service.yaml` template doesn't expose. I am trying to follow the instructions here: [set-administrator-account-and-password](https://pulsar.apache.org/docs/en/administration-pulsar-manager/#set-administrator-account-and-password) from a node in the cluster but it doesn't work. When I go into openshift and manually add the `7750` port to the service I can then set the superuser info.  

**Describe the solution you'd like**
I would like the `pulsar-manager-service.yaml` file to be updated from:
 `ports:
    - name: server
      port: {{ .Values.pulsar_manager.service.port }}
      targetPort: {{ .Values.pulsar_manager.service.targetPort }}
      protocol: TCP`
to:
`ports:
    - name: server
      port: {{ .Values.pulsar_manager.service.port }}
      targetPort: {{ .Values.pulsar_manager.service.targetPort }}
      protocol: TCP
    {{- if .Values.pulsar_manager.service.admin_port }}
    - name: {{ .Values.pulsar_manager.service.admin_port.name }}
      port: {{ .Values.pulsar_manager.service.admin_port.port }}
      targetPort: {{ .Values.pulsar_manager.service.admin_port.targetPort }}
      protocol: TCP
    {{- end }}`

**Describe alternatives you've considered**
The only other options I have are:  
1. Create and maintain my own helm charts (which long term isn't viable)
2. Do this manually (which doesn't allow it to be automated like I need)

**Additional context**
Even if you want to hardcode it instead of making it virialized that would be fine also.

**Comment by alpreu** [comment]
Unfortunately, pulsar-manager does not really support OpenShift yet. You can try @streamvisor, it runs on OpenShift out of the box and is also free :)

**Comment by lhotari** [comment]
> Unfortunately, pulsar-manager does not really support OpenShift yet. You can try @streamvisor, it runs on OpenShift out of the box and is also free :)

Please stop spamming this issue tracker with your advertisements, @alpreu.

**Comment by lhotari** [comment]
Closing this outdated issue. #457 improves the pulsar manager integration.
