### ISSUE TITLE
Missing arguments in prepare_helm_release.sh script

### ISSUE THREAD

**Issue by cvuijst** [apache/pulsar-helm-chart#23]
#### Expected behavior

As of the official documentation of 2.6.0, the **prepare_helm_release.sh** should be able to be configured with:

- control-center-admin
- control-center-password

#### Actual behavior

The result when running the script is:
> unknown option: --control-center-admin

#### Steps to reproduce

- See the documentation at: [http://pulsar.apache.org/docs/en/kubernetes-helm/#step-1-install-pulsar-helm-chart](http://pulsar.apache.org/docs/en/kubernetes-helm/#step-1-install-pulsar-helm-chart).

- Execute step 1 (cloning and changing directory).

- Go to step 2 and copy the contents using the button.

- Paste the content on a cli and see the result.

#### System configuration
**Pulsar version**: 2.6.0

**Comment by sijie** [comment]
@cvuijst Thank you for reporting this. I think those settings were moved to the helm values file to be configured. We might need to update the documentation.

**Comment by grstein** [comment]
Hi @sijie I got the same issue, but I couldn't find any option in the helm chart to set those options.

**Comment by sijie** [comment]
Created an issue to update the documentation. apache/pulsar#7365

**Comment by qq516249940** [comment]
in china how to use  prepare_helm_release.sh ？？？
```bash
curl: (7) Failed to connect to raw.githubusercontent.com port 443: 拒绝连接
generate the token for admin
Get pulsarctl install.sh script ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to raw.githubusercontent.com port 443: 拒绝连接
```
