### ISSUE TITLE
Helm Chart requires ClusterRoles for Pulsar Functions, Promotheus, etc. 

### ISSUE THREAD

**Issue by briedel** [apache/pulsar-helm-chart#246]
ClusterRoles for Pulsar Functions, Promotheus, etc. This is related to issue #173 

`rbac.limit_to_namespace: true` 

only limits required pulsar pieces (broker, bookie, etc.) to the namespace, but not Pulsar function workers, Promotheus. 

Error is:

`Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource ClusterRole "test-prep-pulsar-functions-worker" in namespace "": clusterroles.rbac.authorization.k8s.io "test-prep-pulsar-functions-worker" is forbidden: User "..." cannot get resource "clusterroles" in API group "rbac.authorization.k8s.io" at the cluster scope`

`Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource ClusterRole "test-prp-pulsar-prometheus" in namespace "": clusterroles.rbac.authorization.k8s.io "test-prp-pulsar-prometheus" is forbidden: User "..." cannot get resource "clusterroles" in API group "rbac.authorization.k8s.io" at the cluster scope`

**Comment by lhotari** [comment]
The problem is fixed. Please test with latest release of the helm chart.
