### ISSUE TITLE
Pulsar Manager Username/Password does not work with examples/values-minikube.yaml

### ISSUE THREAD

**Issue by adminnz** [apache/pulsar-helm-chart#254]
**Describe the bug**
When installing the Helm chart with examples/values-minikube.yaml with a modification make it install pulsar_manager.
The puslar manager pod is started along with the service and I can access the login page, but the username "pulsar" and password "pulsar" that are set as environment variables on the pod do not work to login.
Also checking the pulsar-mini-pulsar-manager-secret shows PULSAR_MANAGER_ADMIN_PASSWORD & PULSAR_MANAGER_ADMIN_USER set with "pulsar" (without quotes).

Note: I can login to the Grafana dashboard.

**To Reproduce**
1. Follow the Install Pulsar Helm Chart guide [here](https://pulsar.apache.org/docs/en/kubernetes-helm/#step-1-install-pulsar-helm-chart)
2. modify the examples/values-minikube.yaml file to have pulsar_manager: true set under components.
3. minikube service -n pulsar pulsar-mini-pulsar-manager
4. Go to login page, enter username = "pulsar" and password = "pulsar" without quotes, and it returns "the username or password is incorrect"

**Expected behavior**
The username & password should work

**Screenshots**
![secret_screenshot](https://user-images.githubusercontent.com/1552285/161367184-8afb5aca-94d6-446d-9f9d-25610ded73df.png)

![pulsar-manager-pod_screenshot](https://user-images.githubusercontent.com/1552285/161367104-4158ab6f-7218-4005-8774-df3befb0dc61.png)

**Desktop (please complete the following information):**
 - OS: Windows, with Docker & Minikube
 (Note: I could not run the scripts/pulsar/prepare_helm_release.sh because it doesnt work on windows), so i manually created the namespace.

**Additional context**

**Comment by adminnz** [comment]
I've manged to login by creating a super user using the[ following steps.](https://github.com/apache/pulsar-manager/blob/994ad84ee3b1a73f978e1e31950c961ce4a69cf6/README.md#access-pulsar-manager)
Is there a reason why the helm template username/password does not work?

**Comment by lhotari** [comment]
fixed by #457
