### ISSUE TITLE
Cannot use the default admin username and password to login manager.

### ISSUE THREAD

**Issue by jaggerwang** [apache/pulsar-helm-chart#256]
**Describe the bug**
When tried to login manager, it always shows "The username or password is incorrect".
![image](https://user-images.githubusercontent.com/1255011/162713833-85b0882e-28ac-4b65-b1e4-aa86d9629985.png)

The env command shows the default admin username and password is just pulsar/pulsar.
![image](https://user-images.githubusercontent.com/1255011/162714921-5964f3f7-ee11-4867-b6fc-c6498f230aff.png)

I tried to set the admin username and password like [here](https://pulsar.apache.org/docs/en/administration-pulsar-manager/#set-administrator-account-and-password). But the management port only listen on localhost, and I can't install curl command using apt or yum.

**Additional context**
I'm running pulsar 2.7.4 in Kubernetes 1.21.
![image](https://user-images.githubusercontent.com/1255011/162714129-3c873b62-6395-415b-a9dd-67bac99bc5ce.png)

**Comment by michaeljmarshall** [comment]
@jaggerwang - are you seeing an error in the Pulsar Manager's logs?
