### ISSUE TITLE
pods for broker/bookkeeper init failed - Could not find or load main class "-Xms1g error

### ISSUE THREAD

**Issue by rvashishth** [apache/pulsar-helm-chart#26]
**Describe the bug**
Init container `pulsar-bookkeeper-verify-clusterid fail` fails to start with following stack trace

```
[conf/bookkeeper.conf] Applying config ledgerDirectories = /pulsar/data/bookkeeper/ledgers
[conf/bookkeeper.conf] Applying config statsProviderClass = org.apache.bookkeeper.stats.prometheus.PrometheusMetricsProvider
[conf/bookkeeper.conf] Applying config useHostNameAsBookieID = true
[conf/bookkeeper.conf] Applying config zkLedgersRootPath = /ledgers
[conf/bookkeeper.conf] Applying config zkServers = pulsar-zookeeper:2181
[conf/bookkeeper.conf] Adding config journalDirectories = /pulsar/data/bookkeeper/journal
JMX enabled by default
Error: Could not find or load main class "-Xms1g
JMX enabled by default
Error: Could not find or load main class "-Xms1g
JMX enabled by default
Error: Could not find or load main class "-Xms1g
.
.
```
**To Reproduce**
1. Package a chart with this repo(no change in config)
2. broker, recovery, proxy, bookkeeper pod creation fails 
3. check init container logs `kubectl logs pulsar-bookkeeper-0 -c pulsar-bookkeeper-verify-clusterid -n pulsar`

**Env**
Azure AKS

**Comment by sijie** [comment]
@rvashishth Are you running with the latest master?

**Comment by sijie** [comment]
I don't see `-Xms1g` in the default vaules.ymal file. Can you share your values file?

**Comment by rvashishth** [comment]
@sijie I used this [Values.yml file from](https://github.com/apache/pulsar-helm-chart/blob/6cddb81da148423b7e671b47cdd78758ee3c9b64/charts/pulsar/values.yaml) from the previous commit after PR #22 merged.  I didn't make any changes in this values file. 

looks like some config issue at `bkEnv.sh`

This error looks somewhat similar to these two issues - https://github.com/apache/pulsar/issues/7243, or https://github.com/apache/pulsar/issues/6355

**Comment by sijie** [comment]
@rvashishth please use the latest master to include #24

**Comment by rvashishth** [comment]
@sijie I have tested with the latest master with #28, still the same error with init containers.

**Comment by rvashishth** [comment]
this time zookeeper also going in CrashLoopBackOff status with the below error.

```
$ kubectl logs pulsar-zookeeper-0  -n pulsar
[conf/zookeeper.conf] Applying config dataDir = /pulsar/data/zookeeper
[conf/zookeeper.conf] Adding config serverCnxnFactory = org.apache.zookeeper.server.NettyServerCnxnFactory
Current server id 1
Error: Could not find or load main class "-Xms1g
```

**Comment by lukestephenson-zendesk** [comment]
Similar, I'm trying the latest master and my bookies are now failing to start with:
```
Error: Could not find or load main class "
JMX enabled by default
```

**Comment by rvashishth** [comment]
all pods started successfully.  the previous issue was due to chart being cached.
