### ISSUE TITLE
helm chart for pulsar version 2.10.0

### ISSUE THREAD

**Issue by nvmav** [apache/pulsar-helm-chart#267]

**Comment by Syphixs** [comment]
bump , new version would be gladly appreciated! 
Seems though its not a simple image version upgrade alone

**Comment by Anmol057** [comment]
Hi, When can we expect the 2.10.0 version to be released?

**Comment by hpvd** [comment]
latest pulsar is now 2.10.1 :-)
https://github.com/apache/pulsar/releases/tag/v2.10.1

btw. just looked to the included Prometheus version:
its
v2.17.2 from 2020-04-20  https://github.com/prometheus/prometheus/releases/tag/v2.17.2
while latest is
2.37.0 from 2022-07-14  https://github.com/prometheus/prometheus/releases/tag/v2.37.0 
(which among other things fixed several vulnerabilities during last 2 years...)

**Comment by hpvd** [comment]
if new version of helm chart is released, one should give it a quick check to get the whole picture:
https://artifacthub.io/packages/helm/apache/pulsar?modal=security-report
today it looks pretty mediocre...

**Comment by k3nda** [comment]
Any estimates please? Would be really nice to have update for 2.10.x version :+1:

**Comment by hpvd** [comment]
please see:
helm chart is outdated and includes images with 992 vulnerabilities
https://github.com/apache/pulsar-helm-chart/issues/294

**Comment by majiwhut** [comment]
How about use the latest pulsar helm chart to adapt pulsar v2.10.0?
I don't known in this way whether make the pulsar not work

**Comment by michaeljmarshall** [comment]
Fixed by #267. It will be released in the coming week(s). The timeline is dependent on testing and a vote on the dev@pulsar.apache.org mailing list.
