### ISSUE TITLE
Error while executing prepare_helm_release.sh: tar: Error opening archive: Unrecognized archive format

### ISSUE THREAD

**Issue by bharatbhushan1705** [apache/pulsar-helm-chart#287]
**Describe the bug**
Error while executing prepare_helm_release.sh: tar: Error opening archive: Unrecognized archive format

**To Reproduce**
1. execute the below step:
./scripts/pulsar/prepare_helm_release.sh \
    -n pulsar \
    -k pulsar-mini \
    -c

**Expected behavior**
Getting error when downloading install.sh with curl:
pulsar-helm-chart % ./scripts/pulsar/prepare_helm_release.sh \
    -n pulsar \
    -k pulsar-mini \
    -c
Error from server (AlreadyExists): namespaces "pulsar" already exists
generate the token keys for the pulsar cluster
Get pulsarctl install.sh script ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3987  100  3987    0     0  16557      0 --:--:-- --:--:-- --:--:-- 16965
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     34      0 --:--:-- --:--:-- --:--:--    36
tar: Error opening archive: Unrecognized archive format

**Screenshots**
<img width="648" alt="Screenshot 2022-09-12 at 22 51 02" src="https://user-images.githubusercontent.com/54980167/189757751-a2f7ad68-2967-469e-8118-1b6d302d9d22.png">

**Desktop (please complete the following information):**
 macOS Monterey 12.5.2(21G83)

**Additional context**

**Comment by michaeljmarshall** [comment]
Thanks for your issue @bharatbhushan1705.

> Get pulsarctl install.sh script ...
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 3987 100 3987 0 0 16557 0 --:--:-- --:--:-- --:--:-- 16965
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 9 100 9 0 0 34 0 --:--:-- --:--:-- --:--:-- 36
tar: Error opening archive: Unrecognized archive format

The error is when trying to download `pulsarctl`, which is architecture dependent. It looks like the default is to download v0.4.0, which does not appear to have a build for ARM. Any chance you're building on an M1 Mac? Once we confirm that is the issue, we can figure out a solution.

**Comment by bharatbhushan1705** [comment]
Hello @michaeljmarshall ,

As mentioned earlier I am using macOS Monterey 12.5.2(21G83).
MacBook M1 Pro.

**Comment by bharatbhushan1705** [comment]
Hello Team,

Is there someone who can help me to proceed further?

**Comment by bharatbhushan1705** [comment]
@michaeljmarshall Could you please help me here with some quick steps to solve locally at lease.

**Comment by michaeljmarshall** [comment]
@codelipenghui @wolfstudy @zymap - looks like the Helm Chart script `scripts/pulsar/prepare_helm_release.sh ` depends on `pulsarctl`, and the current one is an old one. We could update the `pulsarctl` dependency so that it works in this scenario, or we could update the chart so that it creates JWT tokens using a kubernetes `Job`. Because the `bin/pulsar` script includes a JWT creation option, I think we might be able to make that work with the same docker image used for the broker docker image. Let me know how you think we should proceed. Thanks!
