### ISSUE TITLE
2.10.0 pulsar helm chart is not published,when will publish?

### ISSUE THREAD

**Issue by majiwhut** [apache/pulsar-helm-chart#293]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by eolivelli** [comment]
Good point.

Currently you can use Pulsar 2.10.x with the latest version of helm chart.
The only thing you need it to override the image versions.

**Comment by majiwhut** [comment]
> 

thank you very much

**Comment by hpvd** [comment]
just opend an issue for this from security pov:
helm chart is outdated and includes images with 992 vulnerabilities
https://github.com/apache/pulsar-helm-chart/issues/294
