### ISSUE TITLE
[security] helm chart is outdated and includes images with 992 vulnerabilities (623 fixable)

### ISSUE THREAD

**Issue by hpvd** [apache/pulsar-helm-chart#294]
**Describe the bug**
helm chart is outdated and includes images with 992 vulnerabilities

In detail:
- there are dependencies with well known security issues (with official CVE numbers)
- there is a pretty huge number of known and documented vulnerabilities: 992
-  including important ones (critical, high rating)
-  not only in the accompanying software in helm (prometheus, grafana) but in core directly (pulsar)
-  some were known for 9 years (CVE numbers from 2013)
- there are possible fixes for most of them (for 623)

see source https://artifacthub.io/packages/helm/apache/pulsar?modal=security-report

Of course, this is only a first rough impression given by this analysis.
And the chart does not contain the very latest version of pulsar (even so, it's the latest official helm chart)
When looking into every detail of the reported numbers, you can of course argue why not every counted vulnerabilities is a disaster...

=> But how can you easily argue to anyone having seen this fast result

>  In general, this software (pulsar) is secure, you can use it without any concerns.

?

This issue is a shortened copy from
Arguments for "why pulsar is secure?"
https://github.com/apache/pulsar/issues/18041
for more details and comments, please see there.

**Comment by hpvd** [comment]
overview from link above:
![2022-10-13_14h16_24](https://user-images.githubusercontent.com/5681880/195624955-095c6fc8-062b-4149-b5bf-c2cfb7a54f2e.png)

**Comment by hpvd** [comment]
more details:
![2022-10-13_14h18_45](https://user-images.githubusercontent.com/5681880/195625079-11db1b5d-b0f3-436b-ae2d-4ee89a5a548c.png)

**Comment by hpvd** [comment]
would/will be very interesting to see, how an updated helm chart with latest pulsar image perform in the same scan.
=> is the update already the big part of the solution?

**Comment by michaeljmarshall** [comment]
@hpvd - thank you for creating this issue. I am going to look into how we can get these issues resolved.

**Comment by hpvd** [comment]
@michaeljmarshall many thanks for starting looking in it that fast
and especially your proposal to make a general approach set the ground to finally solve this (https://github.com/apache/pulsar-helm-chart/pull/299)!

**Comment by hpvd** [comment]
just as background info, the security scanner used by artifacthub, providing results shown above
is trivy, **so all the finding should be pretty valid**.

For details, see:
https://artifacthub.io/docs/topics/security_report/

and trivy
https://github.com/aquasecurity/trivy)

**Comment by michaeljmarshall** [comment]
Thank you for raising this issue @hpvd, and thank you for the extra context. It is very important to get the helm chart into a better place. Part of the reform is updating the release process, which I started here #301. This will take some extra time in the beginning, but should lead to easier releases in the future.

**Comment by hpvd** [comment]
@michaeljmarshall 

there is also an easy to use **github action for scanning with trivy** 
-  the complete repository,
-  pull requests,
- docker container
- IaC
- etc.
 
=> Maybe this is interesting to integrate this directly into the CI pipeline...
See Readme of https://github.com/aquasecurity/trivy-action

**Comment by michaeljmarshall** [comment]
We could definitely investigate using that tool. For now, I am focused on getting the relevant dependencies upgrade and fixing the release process.

**Comment by hpvd** [comment]
wow just saw the latest release 3.0.0!
What a great progress :-)

just did the same quick security check up again:

Latest security analysis show
- a stunning step in reducing the number of included vulnerabilities (minus 85%!)
  - v2.9.4 with pulsar 2.9.3 **1024 vulnerabilities (698 fixable) have been detected in this package's images.**
https://artifacthub.io/packages/helm/apache/pulsar/2.9.4?modal=security-report
  - v3.0.0 with pulsar 2.10.2 **136 vulnerabilities (79 fixable) have been detected in this package's images.**
https://artifacthub.io/packages/helm/apache/pulsar?modal=security-report
- on the other hand
  - the number of fixable vulnerabilities with a severity of CRITICAL has risen from 1 to 4 (plus 300%!)
 
![2022-11-04_10h05_52](https://user-images.githubusercontent.com/5681880/199936712-593036aa-b445-4c6a-990a-4951e5487c28.png)

![2022-11-04_10h07_06](https://user-images.githubusercontent.com/5681880/199936741-a8f2139b-f055-4f2a-b74d-fbdaa59bf909.png)

  - very old fixable and already reported vulnerabilities (up to 9 years old) are still included:
   
![2022-11-04_09h21_54](https://user-images.githubusercontent.com/5681880/199937604-17826ab6-0d4d-469d-a1cd-7df6019138bb.png)

edit: just opened a separate issue for this: https://github.com/apache/pulsar/issues/18338

**Comment by hpvd** [comment]
follow-up issue: https://github.com/apache/pulsar-helm-chart/issues/334

**Comment by michaeljmarshall** [comment]
Since we have a follow up issue, can we close this one @hpvd?

**Comment by hpvd** [comment]
@michaeljmarshall 
Yes I think that's good move!
