### ISSUE TITLE
Pulsar-manager connection refused

### ISSUE THREAD

**Issue by MonicaMagoniCom** [apache/pulsar-helm-chart#295]
Hi all,

I have updated my pulsar cluster from 2.6.1 to 2.10.1 with pulsar-manager version 0.3.0.
I try to login on pulsar-manager with credentials _pulsar/pulsar_ but it fails; from the logs I see:
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is org.postgresql.util.PSQLException: **Connection to 127.0.0.1:5432 refused.** Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

I have also tried to change in the application.properties file "user.management.enable" to "false" but nothing changes.

Even if i run this curl
CSRF_TOKEN=$(curl http://localhost:7750/pulsar-manager/csrf-token)
I got connection refused.

Can someone help me?

Thank you

**Comment by MonicaMagoniCom** [comment]
Yes it is running but I have authentication and authorization enabled on the cluster. I see that by setting the following values:
JWT_TOKEN:<token>
SECRET_KEY: data:base64,<secret key>
pulsar manager receives 401 http code from the brokers when it tries to ask for tenants/namespaces/etc. 

Also, from pulsar manager logs, the jwt token is not used in the header of the request towards the broker.

**Comment by michaeljmarshall** [comment]
Is there any configuration that works? I wouldn't have thought authn/authz would affect this error since the specific error log is a failure related to the JDBC connection, which is not a Pulsar connection. That has to do with connecting to an internal Postgres database running in the Pulsar Manager. I am not familiar with the internals of that project, though.

**Comment by eolivelli** [comment]
It would be also interesting to default to storing the data on HerdDB, that in turn stored the data on the bookies. This will save us to run PostGree

**Comment by MonicaMagoniCom** [comment]
They are two different errors, sorry. The first one is the one I got with pulsar-manager version 0.3.0, while the second related to JWT token happens with 0.2.0 version. It seems that version 0.3.0 has some problems at the login page already.

**Comment by zengzhengrong** [comment]
#https://github.com/apache/pulsar-manager/pull/478

Use tag v0.2.0

**Comment by lhotari** [comment]
Fixed by #457
