### ISSUE TITLE
2.6.0 release tag is missing on the repo

### ISSUE THREAD

**Issue by jharris-** [apache/pulsar-helm-chart#32]
The Chart.yaml was bumped to 2.6.0  but a release tag was not created

**Comment by sijie** [comment]
@jharris- I am working on publishing the package and the tag.

**Comment by sijie** [comment]
@jharris- I have just released the 2.6.0 tag. https://github.com/apache/pulsar-helm-chart/tree/pulsar-2.6.0

The 2.6.0 helm chart has been published to GitHub release: https://github.com/apache/pulsar-helm-chart/releases/tag/pulsar-2.6.0

I  have triggered building the pulsar website. The pulsar helm chart will be published at https://pulsar.apache.org/charts
