### ISSUE TITLE
Release 3.0.0 using Apache Pulsar 2.10.2

### ISSUE THREAD

**Issue by michaeljmarshall** [apache/pulsar-helm-chart#326]
This issue will track the progress of the 3.0.0 release.

**Comment by michaeljmarshall** [comment]
Tag 3.0.0-candidate-1 is out for vote. Here is the mailing list thread: https://lists.apache.org/thread/b02r3605jvmom23p1ccjbzsfwrq5tkjv.

**Comment by hpvd** [comment]
wow this was really fast work!!

**Comment by hpvd** [comment]
just an idea:
with having a good overview of this repository in mind from all the done work,
maybe it's a good moment to look quickly through the list of open issues and pull requests, if there aren't some which
- were already solved or
- become unnecessary or
- are obsolete
and could simply be closed **without further investigations/work**.

-> With this, 3.0 would even have a fresher start :-)

**Comment by hpvd** [comment]
would be nice to put a README into the helm chart, see https://github.com/apache/pulsar-helm-chart/issues/328

**Comment by hpvd** [comment]
would be a bonus to even include the changelog (since it's a major version bump, it may be even more interesting/ important)
https://github.com/apache/pulsar-helm-chart/issues/329

**Comment by michaeljmarshall** [comment]
Those are great suggestions @hpvd. I started to look into those, but I prioritized getting a release out. Thank you for creating those issues.

I took a look at open issues and PRs last week and tried to merge the ones that seemed important. If there is anything missing, we can get it for the next release. These releases shouldn't be too hard to complete once we have a finalized process.

**Comment by hpvd** [comment]
+1 for setting the right prio!

**Comment by michaeljmarshall** [comment]
The vote is completed: https://lists.apache.org/thread/7605rrsvgbkyll3xk00ft9jofo839g5k. I will work on publishing the release artifacts and then I'll announce the release.

**Comment by michaeljmarshall** [comment]
This release is now available.
