### ISSUE TITLE
How to get values?

### ISSUE THREAD

**Issue by exipnus** [apache/pulsar-helm-chart#330]
**Describe the bug**
```
helm get values pulsar-2.9.4 > pulsar.yaml
```
fails with message: 

```
Error: release: not found
```

**To Reproduce**
1. helm get values pulsar-2.9.4 > pulsar.yaml

**Expected behavior**
Expected pulsar.yaml with default chart values to be created

**Screenshots**
![image](https://user-images.githubusercontent.com/85255193/198034509-f811c23f-dfbd-4aea-9943-ae1562d69f91.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu-22.04
 - helm: v3.10.1

I apologize but I am newbie on helm charts and it is unclear from the documentation (https://pulsar.apache.org/docs/helm-overview#upgrading) how to get the values.

Thank you

**Comment by michaeljmarshall** [comment]
> Expected pulsar.yaml with default chart values to be created

The `helm get values` command does not provide the default values. It gets the values for a "named release", which means an already installed instance of the helm chart.
