### ISSUE TITLE
[security] further reduction of the 136 vulnerabilities (79 fixable) in helm chart v3.0.0

### ISSUE THREAD

**Issue by hpvd** [apache/pulsar-helm-chart#334]
This is the follow-up issue to https://github.com/apache/pulsar-helm-chart/issues/294

we did a huge step forward in the field of security with the release of helm chart v3.0.0
(for details see summary in https://github.com/apache/pulsar-helm-chart/issues/294#issuecomment-1303176871)

When looking into the latest version, there are still
**136 vulnerabilities (79 fixable) have been detected in this package's images.**
containing:
- 4 vulnerabilities with a CRITICAL severity (4 fixable) 
- 23 vulnerabilities with a HIGH severity (23 fixable)
- 45 vulnerabilities with a MEDIUM severity (29 fixable)

see https://artifacthub.io/packages/helm/apache/pulsar?modal=security-report

-> (1) **For about half of the number of vulnerabilities, we are fully in control and in the responsibility of pulsar community**:
(in attachment colored ORANGE)
- 72 vulnerabilities have been detected in the image 
`apachepulsar/pulsar-all:2.10.2`
- 35 of these should be fixable with a version bump of dependencies.

-> (2) **The other half of vulnerabilities comes from tools we include** in the helm chart and could not be fully controlled.
These tools introduce
- 3 of 4 vulnerabilities with a CRITICAL severity
- 21 of 23 vulnerabilities with a HIGH severity

The only obvious thing that may help a little to reduce these half of the number of vulnerabilities,
would be to make sure to `always include the very latest version` of these tools
(in attachment, the tools not up to date are colored YELLOW)
The impact shouldn't be very large since the included versions are not very old, but maybe notable.

=> What else can/should we do?

Overview:
![2022-11-04_15h40_56](https://user-images.githubusercontent.com/5681880/200014439-8e077c22-03b9-4c23-b459-7c192ed153fc.png)

**Comment by hpvd** [comment]
Details for Part (1):

![2022-11-04_17h06_11](https://user-images.githubusercontent.com/5681880/200023011-23e1244c-fdcc-4d6f-8562-947965b135b4.png)

![2022-11-04_17h03_17](https://user-images.githubusercontent.com/5681880/200023069-43303c65-e7f5-454e-be09-c283a0170a42.png)

**Comment by hpvd** [comment]
Details for Part (2):
latest versions of tools included in helm chart

- https://github.com/grafana/grafana/releases 9.2.3 (2022-10-31)
- https://github.com/kiwigrid/k8s-sidecar/releases v1.19.5 (2022-09-15)
- https://github.com/prometheus/prometheus/releases 2.39.1 (2022-10-07)
- https://github.com/prometheus/node_exporter/releases 1.4.0 (2022-09-24)
- https://github.com/prometheus-operator/prometheus-operator/releases 0.60.1 (2022-10-10)
- https://github.com/kubernetes/kube-state-metrics/releases v2.6.0 (2022-08-26)

**Comment by hpvd** [comment]
just openend an issues for Part (1): https://github.com/apache/pulsar/issues/18348

so this is mostly about Part (2)

**Comment by hpvd** [comment]
update: todays state

206 vulnerabilities (123 fixable) have been detected in this package's images.

![2022-12-21_15h19_49](https://user-images.githubusercontent.com/5681880/208927186-ac16f516-70bc-4d98-a7cb-d8e1535da4ed.png)


https://artifacthub.io/packages/helm/apache/pulsar?modal=security-report

**Comment by lhotari** [comment]
Closing this issue since the latest release is 3.2.0 . The next release 3.3.0 will upgrade kube-prometheus-stack to 56.x so that will address some problems.

**Comment by hpvd** [comment]
upgrade kube-prometheus-stack sounds great!

The current state of  v3.2.0:
241 vulnerabilities (200 fixable) have been detected in this package's images.
![2024-02-15_17h55_24](https://github.com/apache/pulsar-helm-chart/assets/5681880/8782210e-9fb6-475e-ac62-b8e5ae4480ec)

**Comment by hpvd** [comment]
just an update on this:

The current state of v3.3.0:
205 vulnerabilities (150 fixable) have been detected in this package's images.
source: https://artifacthub.io/packages/helm/apache/pulsar?modal=security-report

![2024-03-15_16h02_08](https://github.com/apache/pulsar-helm-chart/assets/5681880/c2ebbcc2-1f62-4648-a8c2-bed2f80a4bc3)

**Comment by lhotari** [comment]
> just an update on this:
> 
> The current state of v3.3.0: 205 vulnerabilities (150 fixable) have been detected in this package's images. source: https://artifacthub.io/packages/helm/apache/pulsar?modal=security-report

thanks @hpvd . There's 3.3.1 in voting, please see https://lists.apache.org/thread/2f3mx74o52xsxvt1y72phxk1jxl5tt60 .
In the Apache Pulsar Helm chart project, there is a shortage of active contributors to the project. I'd highly appreciate pull requests to address security vulnerabilities so that things could improve. This is a community driven project and it won't move forward without contributors that volunteer to improve things. If you would be interested in contributing, I could help in getting started.
