### ISSUE TITLE
PULSAR_MEM variable doesn't set limits for bookie

### ISSUE THREAD

**Issue by Shohou** [apache/pulsar-helm-chart#350]
**Describe the bug**
I found that changing `PULSAR_MEM` variable for bookkeeper which can be found in `values.yaml` file doesn't change memory params of bookie at least for pulsar v2.9.4
Some investigation shows that in version 2.6.x `bin/pulsar` script had this line
```
OPTS="$OPTS $PULSAR_EXTRA_OPTS $PULSAR_MEM $PULSAR_GC"
```
from version 2.7.x till 2.9.x it has this:
```
if [ $COMMAND == "bookie" ]; then
  # Pass BOOKIE_EXTRA_OPTS option defined in bkenv.sh
  OPTS="$OPTS $BOOKIE_EXTRA_OPTS"
else
  OPTS="$OPTS $PULSAR_EXTRA_OPTS $PULSAR_MEM $PULSAR_GC"
fi
```
and versions 2.10.x - 2.11.x has this:
```
if [ $COMMAND == "bookie" ]; then
  # Pass BOOKIE_EXTRA_OPTS option defined in bkenv.sh
  OPTS="$OPTS $BOOKIE_MEM $BOOKIE_GC $BOOKIE_GC_LOG $BOOKIE_EXTRA_OPTS"
else
  OPTS="$OPTS $PULSAR_MEM $PULSAR_GC $PULSAR_GC_LOG $PULSAR_EXTRA_OPTS"
fi
```

I think it could be changed to BOOKIE_MEM with some comment about earlier versions

**Comment by lhotari** [comment]
`PULSAR_MEM` has been supported for a very long time as a fallback. There's no need to do anything. Old version of Pulsar aren't supported anyways. There are severe known security issues and that's a clear reason to upgrade to supported versions. Supported versions: https://pulsar.apache.org/contribute/release-policy/#supported-versions

**Comment by Shohou** [comment]
@lhotari https://github.com/apache/pulsar-helm-chart/blob/4daf6d88a2417668fadfb6638145b13bbe08122c/charts/pulsar/values.yaml#L587 - if it's not supported then why it's still there?
