### ISSUE TITLE
Please add the missing 3.0.0 release artifact into releases page

### ISSUE THREAD

**Issue by lk-1984** [apache/pulsar-helm-chart#358]
Please add the missing 3.0.0 release artifact into releases page.

**Comment by dave2wave** [comment]
Do you mean this page? https://pulsar.apache.org/download/

**Comment by lk-1984** [comment]
> Do you mean this page? https://pulsar.apache.org/download/

This one

https://github.com/apache/pulsar-helm-chart/releases/tag/pulsar-3.0.0

So the actual release URL is this one:

https://github.com/apache/pulsar-helm-chart/releases/download/pulsar-2.9.4/pulsar-2.9.4.tgz

And as it is missing for the 3.0.0, then in my automation I would have to change the URL to this:

https://github.com/apache/pulsar-helm-chart/archive/refs/tags/pulsar-3.0.0.tar.gz

And of course I would like it to be like this

https://github.com/apache/pulsar-helm-chart/releases/download/pulsar-${PULSAR_VERSION}/pulsar-${PULSAR_VERSION}.tgz

**Comment by michaeljmarshall** [comment]
The helm chart index is hosted here: https://pulsar.apache.org/charts/index.yaml. The index points to https://downloads.apache.org/pulsar/helm-chart/3.0.0/pulsar-3.0.0.tgz for the 3.0.0 release, and the pattern should continue to be as you suggested. Does that solve your request?

**Comment by tisonkun** [comment]
I second @michaeljmarshall's comment above should solve this issue. @lk-1984 does it answer your question?
