### ISSUE TITLE
override toolset image

### ISSUE THREAD

**Issue by relief-melone** [apache/pulsar-helm-chart#363]
At the moment from what I can see in the templates the image of the toolset will be the same as the one of the broker

`image: "{{ template "pulsar.imageFullName" (dict "image" .Values.images.broker "root" .) }}"`

It would be nice if it was possible to override that. For example usually I use the image of the broker but for the toolset add some more tools as well as setting a few aliases for convenience. It would be nice if it was possible to not hard wire the image to the one used for the broker.

**Comment by lhotari** [comment]
covered by #507
