### ISSUE TITLE
Support Apache Pulsar v3.0.0

### ISSUE THREAD

**Issue by dalbani** [apache/pulsar-helm-chart#364]
**Is your feature request related to a problem? Please describe.**
Apache Pulsar v3.0.0 has been released on 2023-05-02, as shown on https://pulsar.apache.org/release-notes/.
The latest release of the chart (v3.0.0) currently deploys Apache Pulsar v2.10.2 (released on 2022-10-28) by default:
https://github.com/apache/pulsar-helm-chart/blob/c8f5e7f9ce596cbc6343feccb8cbe7e698803d8d/charts/pulsar/Chart.yaml#L21

**Describe the solution you'd like**
The chart should support Apache Pulsar v3.0.0.
If not easily possible in a short timeframe, the chart should at least deploy the latest v2.x release (v2.11.1 at the time of writing).

**Describe alternatives you've considered**
I've looked at alternative Helm charts for Apache Pulsar provided by 3rd parties, but all of them are still on v2.x as well.

**Comment by whg517** [comment]
It's been about a month since pulsar 3.0.0 was released and three weeks since pulsar_mnager 0.4.0 was released. I wonder when the community plans to release charts with new versions of pulsar and pulsar_manager?

**Comment by fracasula** [comment]
Backlinking [our issue](https://github.com/apache/pulsar/issues/20571) here.

It would be nice to at least get some clarification in terms of which helm charts and Pulsar version should be used in a production environment.

**Comment by Mortom123** [comment]
Linking #380, as it seems the amount of people wanting to upgrade rises and Pulsar already has released v3.1. 
It would be great if the helm chart could be updated accordingly to use pulsar v3+, as deploying it on your own is major undertaking (at least for me) 
PR #366 is unmerged so far with the comment
> the `apachepulsar/pulsar-all:3.0.0` image is not valid, see https://github.com/apache/pulsar/issues/20420 . It's better to postpone updating to 3.0.x until 3.0.1 has been published.
_Originally posted by @lhotari in https://github.com/apache/pulsar-helm-chart/issues/366#issuecomment-1629635687_

which was released during late August.
I'm completely new to k8s / pulsar hence I'm not of much help but I am willing to test if needed. :)

**Comment by hpvd** [comment]
maybe this is on option: using pulsar operator:
https://operatorhub.io/operator/pulsar-operator
