### ISSUE TITLE
Pulsar manager backend failed to start on v0.4.0

### ISSUE THREAD

**Issue by packageman** [apache/pulsar-helm-chart#365]
**Describe the bug**

The pulsar manager backend keeps getting restarted.

https://github.com/apache/pulsar-manager/issues/517

**Screenshots**

<img width="1150" alt="image" src="https://github.com/apache/pulsar-helm-chart/assets/12949466/1fa1dbed-372e-4c57-be8e-f4659289944c">

<img width="964" alt="image" src="https://github.com/apache/pulsar-helm-chart/assets/12949466/968b6512-cb58-4a7d-9b8d-4a60fee37cf8">

**Comment by frodeopdahl** [comment]
I am having the same issue, but with all versions of Pulsar manager that I have tested. From reading the pulsar-manager.logs it seems to be a problem with connecting with the postgres db?

**Comment by gh777777** [comment]
> > I am having the same issue, but with all versions of Pulsar manager that I have tested. From reading the pulsar-manager.logs it seems to be a problem with connecting with the postgres db?
> 
> Me too! My Pulsar Manager version in pulsar-helm-chart is v0.3.0. Here is the pulsar-manager.log:
> ......

For v0.3.0, [here is a fix](https://github.com/apache/pulsar-manager/issues/505#issuecomment-1385176693).

**Comment by shlomitubul** [comment]
I did try to run it on OpenShift but it didn't work (I add the ENV var), the backend kept crashing

**Comment by alpreu** [comment]
@shlomitubul pulsar-manager does not support running on OpenShift. You can try @streamvisor as a free alternative though

**Comment by shlomitubul** [comment]
@alpreu interesting, can you elaborate why? aside from things like running as root that can be solved by proper scc

**Comment by alpreu** [comment]
> @alpreu interesting, can you elaborate why? aside from things like running as root that can be solved by proper scc,

You would have to change the pulsar-manager docker image but the project is not really maintained anymore (there is a thread on the pulsar mailing list asking for maintainers)

> regarding streamvisor, I saw license secret so im wondering if it free
We offer a paid version with enterprise features such as RBAC etc. but the community version is completely free

**Comment by shlomitubul** [comment]
I able to make it working, you can take alook [here](https://stackoverflow.com/questions/73824661/apache-pulsar-pulsar-manager/77815548#77815548)

**Comment by lhotari** [comment]
Fixed by #457

**Comment by lhotari** [comment]
> We offer a paid version with enterprise features such as RBAC etc. but the community version is completely free

@alpreu Please stop spamming Apache issue trackers with your advertisements. That is completely inappropriate.
