### ISSUE TITLE
Can not install in OpenShift or maybe any else k8s environments with PodSecurityPolicy enabled

### ISSUE THREAD

**Issue by cdmikechen** [apache/pulsar-helm-chart#374]
**Describe the bug**
While installing helm, I found that k8s can't create the first pod by Job `pulsar-mini-kube-prometheu-admission-create` in the first step.
After checking, it was found that the pulsar installation does not support K8s with tighter restrictions on container or PodSecurityPolicy enabled. 

Is it my understanding that helm deployments are not available for production environments yet?

**To Reproduce**
```shell
helm install \
    --values ./values-openshift.yaml \
    --namespace pulsar \
    pulsar ./charts/pulsar
Error: INSTALLATION FAILED: failed pre-install: timed out waiting for the condition
```

**Expected behavior**

**Screenshots**
![image](https://github.com/apache/pulsar-helm-chart/assets/12069428/b9fdb5e9-5ecb-4ab4-92bd-0d10488f6635)

**Desktop (please complete the following information):**
 - OS: OpenShift 4

**Additional context**

**Comment by cdmikechen** [comment]
bookeeper and zookeeper also have this problem:
![image](https://github.com/apache/pulsar-helm-chart/assets/12069428/b07355e5-6a9b-4c3b-9feb-1ccee255f046)

**Comment by cdmikechen** [comment]
I've temporarily manually bound a few openshift permissions and am currently pulling image. 
However, I've found that the PodSecurityPolicy resource will be unavailable at 1.25.
```
W0724 14:45:03.839188   30985 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0724 14:45:03.844912   30985 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0724 14:45:03.850366   30985 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0724 14:45:03.855862   30985 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0724 14:45:03.862282   30985 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0724 14:45:03.871034   30985 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0724 14:45:04.721243   30985 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0724 14:45:04.721809   30985 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0724 14:45:04.722587   30985 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0724 14:45:04.722694   30985 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0724 14:45:04.723155   30985 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0724 14:45:04.723338   30985 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
```

**Comment by cdmikechen** [comment]
Another question I have is why does pulsar use one all-image instead of splitting into different images for different components?

**Comment by lhotari** [comment]
> Another question I have is why does pulsar use one all-image instead of splitting into different images for different components?

Please discuss this on Pulsar Slack or GitHub Discussions, see https://pulsar.apache.org/community/#section-discussions

**Comment by lhotari** [comment]
It should be possible to deploy on OpenShift. Please open another issue if it doesn't work with the latest chart release.
