### ISSUE TITLE
version:2.9.3  ， porMonitor for proxy doesn't get metric data, the prometheus report "server returned HTTP status 401 Unauthorized"

### ISSUE THREAD

**Issue by aa1215018028** [apache/pulsar-helm-chart#377]
**version:2.9.3  when I open the jwt feature for cluster, the porMonitor for proxy doesn't get metric data, the prometheus report "	server returned HTTP status 401 Unauthorized", but the podmonitor for bookie,broker,zookeeper is  noraml,  I know the http request need certify, but i don't know how to add the admin'token. How should I solve this problem?**

**Comment by mnit016** [comment]
hello @aa1215018028 , how about try adding this env to proxy configData:
```
proxy:
  configData:
    authenticateMetricsEndpoint: "false"
```

**Comment by lhotari** [comment]
Version 2.9.3 isn't supported. Please check the release policy of Apache Pulsar here: https://pulsar.apache.org/contribute/release-policy/#supported-versions . Please upgrade to the latest version of the Apache Pulsar Helm chart and use the Pulsar LTS version 3.0.x  (3.0.2 currently).
