### ISSUE TITLE
Error 404 in csrf-token and login in Pulsar Manager

### ISSUE THREAD

**Issue by olsenpabu** [apache/pulsar-helm-chart#388]
**Describe the bug**
At the landing page csrf-token is showing error 404.
Attempting to login is showing error 404

**To Reproduce**
1. Deployed pulsar in AWS environment using helm charts
2. Opened the landing page of pulsar manager
3. Login using admin credentials

**Expected behavior**
Able to login and csrf-token exists

**Screenshots**
<img width="1470" alt="Screenshot 2023-08-25 at 5 10 48 PM" src="https://github.com/apache/pulsar-helm-chart/assets/143013093/652f3dec-3441-4bdd-b9f1-3bd077cb7853">

**Desktop (please complete the following information):**
 - OS: AL2

**Additional context**

**Comment by lhotari** [comment]
#457 improves the pulsar manager integration. closing this issue.
