### ISSUE TITLE
Pulsar Manager Error 404 - Missing CSRF Token

### ISSUE THREAD

**Issue by olsenpabu** [apache/pulsar-helm-chart#390]
**Describe the bug**
Using Helm chart to deploy pulsar manager. All pods are up and running. When accessing pulsar manager it throws missing CSRF Token. 
**To Reproduce**
1. Used Helm Package to deploy pulsar in Kubernetes setup
2. Configured values.yaml to have a superuser to access the pulsar manager
3. Accessed pulsar manager
Observation: Error 404 - Missing CSRF Token shows in logs. Tried to login, also shows Error 404.

**Expected behavior**
Able to login and access pulsar manager.

**Screenshots**
![image](https://github.com/apache/pulsar-helm-chart/assets/143013093/c7b8320b-a267-4a54-ac8b-7d6001c37f2f)

**Desktop (please complete the following information):**
 - OS: macOS

**Additional context**
Same issue in local and AWS

**Comment by timoangerer** [comment]
I can confirm this issue on my end. I've followed the getting started guide and get the same error.

**Comment by willzhang** [comment]
same here with pulsar v2.10.2

**Comment by zhixiangjoy** [comment]
same problem!

**Comment by alpreu** [comment]
You can try https://github.com/streamvisor as an enterprise-grade alternative to pulsar-manager. It's free :)

**Comment by lhotari** [comment]
> You can try @streamvisor as an enterprise-grade alternative to pulsar-manager. It's free :)

@alpreu Please remove your advertisements from all Apache Pulsar repositories.

**Comment by lhotari** [comment]
#457 improves pulsar manager integration. Closing this issue.

**Comment by mariemonks-toast** [comment]
I'm running into this as well with version 0.4.0, has anyone found a solution to this?
