### ISSUE TITLE
Error: unable to build kubernetes objects from release manifest - Validation Error

### ISSUE THREAD

**Issue by ptirupac-tibco** [apache/pulsar-helm-chart#40]
**Describe the bug**
Consistently get the following error stack when running **_helm install_**

`Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].ports[0]): missing required field "containerPort" in io.k8s.api.core.v1.ContainerPort`

**Assumptions**
1. k8s setup
2. HELM available

**To Reproduce**
1. git clone https://github.com/apache/pulsar-helm-chart.git
2. git checkout master
3. cd pulsar-helm-chart
4. scripts/pulsar/prepare_helm_release.sh -n pulsar -c
5. helm install --generate-name --values=$PWD/examples/values-one-node.yaml charts/pulsar

**Expected behavior**
`NAME: pulsar-********
LAST DEPLOYED: *****
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None`

**Screenshots**
![pulsar-helm-error](https://user-images.githubusercontent.com/63665447/87624527-9fdf9400-c6ed-11ea-99f3-d01c63b3c1ea.png)

**Desktop (please complete the following information):**
 - macOS - 10.15.5
 - Docker Desktop - 2.3.0.3
 - Kubernetes - v1.16.5
 - HELM - v3.1.1

**Comment by NiklasWagner** [comment]
Same issue. Its a wrong port variable reference in grafana-deployment.yaml and pulsar-manager-deployment.yaml. I'll do a PR on github.
