### ISSUE TITLE
Pulsar default password not working

### ISSUE THREAD

**Issue by kssanthosh** [apache/pulsar-helm-chart#407]
**Describe the bug**

**To Reproduce**
1. I have used helm chart 

> helm repo add apache https://pulsar.apache.org/charts
> 
> helm repo update
> 
> helm install pulsar apache/pulsar    --timeout 10m  --values values.yaml --version 3.0.0 

Using values.yaml

[values.txt](https://github.com/apache/pulsar-helm-chart/files/13280599/values.txt)

5. See error

![pulsaar-new](https://github.com/apache/pulsar-helm-chart/assets/32116883/8ba033de-1c8f-45da-b53c-1bd558bda497)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by alpreu** [comment]
You can try @streamvisor as an enterprise-grade alternative to pulsar-manager. It's free :)

**Comment by lhotari** [comment]
> You can try @streamvisor as an enterprise-grade alternative to pulsar-manager. It's free :)

@alpreu please don't spam Apache issue tracker with advertisements.

**Comment by lhotari** [comment]
Fixed by #457
