### ISSUE TITLE
Function Worker / Broker RBAC alignment

### ISSUE THREAD

**Issue by Mortom123** [apache/pulsar-helm-chart#426]
**Is your feature request related to a problem? Please describe.**
Right now `broker-rbac.yaml` basically just performs work regarding function workers. This file should be renamed accordingly (`function-worker-rbac.yaml`). 
`broker-cluster-role-binding.yaml` can then be renamed to `broker-rbac.yaml` aligning with the rest of the templates. 

Both, function-workers and broker, are the only ones having `-rbac.yaml`'s then. maybe changing to `psp` is more suited here aswell.

**Describe the solution you'd like**
see above

**Describe alternatives you've considered**
None.

**Additional context**
Willing to submit a PR :)

**Comment by lhotari** [comment]
@Mortom123 Yes, it makes sense what you are proposing. I'm looking forward to your PR.
