### ISSUE TITLE
Requires AWS access/secret key when offload driver is set to aws-s3

### ISSUE THREAD

**Issue by nathanclayton** [apache/pulsar-helm-chart#465]
**Describe the bug**
When the offload driver is set to aws-s3, you have to set a secret with the values of AWS_ACCESS_KEY_ID and AWS _SECRET_KEY_ID. These are not necessary if you're using IAM roles tied to the Kubernetes service account to grant access to the S3 bucket

**To Reproduce**
1. Create a new deployment where offload driver is set to `aws-s3` and the secret name is blank
2. Deploy
3. The following error will pop up in the broker stateful set:
```
create Pod pulsar-broker-0 in StatefulSet pulsar-broker failed error: Pod "pulsar-broker-0" is invalid: [spec.containers[0].env[0].valueFrom.secretKeyRef.name: Invalid value: "": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.containers[0].env[1].valueFrom.secretKeyRef.name: Invalid value: "": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
```

**Expected behavior**
Able to deploy with the `aws-s3` offload driver without needing to use access keys

**Desktop (please complete the following information):**
 - OS: AWS EKS 1.29

**Additional context**
The line that is causing this appears to be [here](https://github.com/apache/pulsar-helm-chart/blob/be62fef11c486e9b3e23f3739915c110df84d897/charts/pulsar/templates/broker-statefulset.yaml#L270).

**Comment by lhotari** [comment]
@nathanclayton Thanks for the issue report. Would you have a chance to contribute the fix to this problem?

**Comment by nathanclayton** [comment]
@lhotari - PR made as #466
