### ISSUE TITLE
not able to login to pulsar UI

### ISSUE THREAD

**Issue by rahuldstk** [apache/pulsar-helm-chart#467]
i have used pulsar-3.3.0  in my Kubernetes cluster and all the pods are running included the pulsar-manager-0.  i changed the service type to LoadBalancer of the service: pulsar-pulsar-manager.
 in the yaml :
` admin:
    ui_username: "pulsar"
    ui_password: "pulsarpassword" # leave empty for random password
    db_username: "pulsar"
    db_password: "pulsarpasswordDB" # leave empty for random password`
i have given. but when i try to login using the UI with the above credentials , i am not able to login and its saying "The username or password is incorrect".

in yaml there is a command:` kubectl get secret -l component=pulsar-manager -o=jsonpath="{.items[0].data.UI_PASSWORD}" | base64 --decode`
but this is not returning anything but throwing an error saying: 
```
error: error executing jsonpath "{.items[0].data.UI_PASSWORD}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
        template was:
                {.items[0].data.UI_PASSWORD}
        object given to jsonpath engine was:
                map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":"", "selfLink":""}}
```

**To Reproduce**
1. login to cluster.
2. git clone -b pulsar-3.3.0 https://github.com/apache/pulsar-helm-chart.git
3.  go to pulsar-helm-chart folder
4.  ./scripts/pulsar/prepare_helm_release.sh -n pulsar -k pulsar //pulsar is a namespace already created.
5. helm install --set initialize=true pulsar apache/pulsar -n pulsar -f./charts/pulsar/values.yaml
6. in services, find pulsar-pulsar-manager service and make its type as LoadBalancer which will give a IP
7.  open this IP and we can see admin pulsar UI login page
8. use the credentials we gave in pulsar yaml and click login

**Expected behavior**
should be allowed to login and see the UI with namespace and tenants options.

**Desktop 
 - windows

**Comment by lhotari** [comment]
@Mortom123 do you have a chance to check the problem? thanks

**Comment by yuweisung** [comment]
Dose this work? 
https://pulsar.apache.org/docs/3.1.x/administration-pulsar-manager/#set-the-administrator-account-and-password

**Comment by Mortom123** [comment]
Can check tomorrow, ping me if I forget. @rahuldstk

**Comment by Mortom123** [comment]
You are installing into the `pulsar` namespace, judging by your `prepare_helm_release` command @rahuldstk. 
You also need to run the command to retrieve the secret inside this namespace then, like:
```
kubectl get secret -n pulsar -l component=pulsar-manager -o=jsonpath="{.items[0].data.UI_PASSWORD}" | base64 --decode
```

Forwarding the manager via:
```
kubectl port-forward -n pulsar $(kubectl get pods -n pulsar -l component=pulsar-manager -o jsonpath='{.items[0].metadata.name}') 9527:9527
```
works for me and I can login at `localhost:9527` using `pulsar` and `pulsarpassword`.

I do not use the `prepare_helm_release.sh` command.

**Comment by rahuldstk** [comment]
thank you @Mortom123 . the above command with my namespace specified in starting, worked and i got the random password which was generated. 
but , after the 1st revision of helm install, i had upgraded the helm revision by specifying the password and username, but it seems that is not reflected...
1) is there a way to refresh it so that it will use the latest password specified?
2) in the pulsar doc, prepare_helm_release.sh command is written to be run. So is this command required to be run or can we directly run the install command?

**Comment by Mortom123** [comment]
@rahuldstk, there is currently no way to update the pulsar manager password using this helm chart and I'm also unsure if the manager itself supports this without accessing its internal database. Maybe you can do it in the UI?
The easiest way would probably be to reset the manager and then run the init job again.

**Comment by rahuldstk** [comment]
okay, got it @Mortom123 
thanks a lot for the help guys.
with this command: kubectl get secret -n pulsar -l component=pulsar-manager -o=jsonpath="{.items[0].data.UI_PASSWORD}" | base64 --decode
i was able to get the password and login.
