### ISSUE TITLE
Latest chart version: 3.4.0 missing in the Apache helm repo index

### ISSUE THREAD

**Issue by afernandez-01** [apache/pulsar-helm-chart#490]
The details for this chart version are missing in the helm repo index https://pulsar.apache.org/charts/index.yaml
Would appreciate any guidance as there are a few updates on your most recent manifests for the Pulsar-manager I would like to leverage.

**Comment by lhotari** [comment]
> The details for this chart version are missing in the helm repo index https://pulsar.apache.org/charts/index.yaml Would appreciate any guidance as there are a few updates on your most recent manifests for the Pulsar-manager I would like to leverage.

Unfortunately, the release vote hasn't completed. https://lists.apache.org/thread/t4vlvk0nwd3gzo50t466cqy5h95l81gb .
I'll follow up on the release voting thread.

**Comment by lhotari** [comment]
chart version 3.4.0 has been released: https://lists.apache.org/thread/hwx0944nf37twhxfl8rsf76q6qd0phkm

**Comment by afernandez-01** [comment]
Awesome! Thank you.
