### ISSUE TITLE
Plugins support

### ISSUE THREAD

**Issue by aqeelat** [apache/pulsar-helm-chart#491]
**Is your feature request related to a problem? Please describe.**
We're currently using streamnative protocol plugins and it would be great if we can just set a list urls or local files in the chart and then have them added in the relevant pods (or all).

**Describe the solution you'd like**
Possible solutions:
1. adding a top level section in values.yaml called `plugins` and then we can add the stuff we want to it
2. allowing us to declare custom initContainers (#240)

**Describe alternatives you've considered**
1. custom images (was an overkill)
2. using volumeMounts. This a good option but it means we have to download the plugins and prepare the mounted directory ourselves. I'm not sure how this will play with argo but I didn't test it.
3. using converting the chart into a Kustomize and then adding the initContainers. (Yet to be tested) [approach 1](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/chart.md) or probably [approach 2](https://github.com/thomastaylor312/advanced-helm-demos/tree/master/post-render)

**Additional context**
This will be a quality of life improvement for us.

**Comment by lhotari** [comment]
@aqeelat Contributions are welcome!
