### ISSUE TITLE
Specifying image pull policy in the chart

### ISSUE THREAD

**Issue by grigorizaika1** [apache/pulsar-helm-chart#506]
**Is your feature request related to a problem? Please describe.**
The `.Values.images.functions.pullPolicy` setting is missing from the chart, unlike other components. New functions and connectors get created/updated much more often than other components are updated. This means that there's no way for the new functions and connectors to dynamically track the image updates.

**Describe the solution you'd like**
A working `.Values.images.functions.pullPolicy` setting

**Comment by lhotari** [comment]
covered by #507
