### ISSUE TITLE
template error in 2.6.0-2

### ISSUE THREAD

**Issue by Syphixs** [apache/pulsar-helm-chart#51]
**Describe the bug**
Template error when trying to install the newest verision.

Error: template: pulsar/templates/zookeeper-podmonitor.yaml:21:8: executing "pulsar/templates/zookeeper-podmonitor.yaml" at <$.Values.zookeeper.podMonitor.enabled>: nil pointer evaluating interface {}.enabled

**To Reproduce**
1. download newest master release
2. unpack it
3. helm install --set initialize=true pulsar -f pulsar-2.6.0-2/values.yaml ./pulsar-2.6.0-2/
**Expected behavior**
a succesfull install of helm chart

**Screenshots**
![image](https://user-images.githubusercontent.com/33832024/90116231-7d28b580-dd55-11ea-8fbf-c4550f6a4a9f.png)

**Desktop (please complete the following information):**
 - OS: IOS

**Additional context**
had hoped this release would fix the init container errors from pulsar-broker.

**Comment by Syphixs** [comment]
Okay it seems the problem comes from my value file which is kinda strange. I disabled monitoring.
Here is my file:

/Users/huttes/og/kubernetes/pulsar/pulsar-2.6.0-2/values.yaml

**Comment by toneill818** [comment]
Did you change the default values.yaml file? Looking at your screenshot it looks like you are pointing to the values.yaml file within the chart.

**Comment by Syphixs** [comment]
yeah i did change them.
Do you think it's an indentation problem?

**Comment by toneill818** [comment]
You don't want to change the values.yaml file in the release. Those hold all the default values and is why you are getting the error. You will want to put your values in a different file and reference them with the `-f` flag. That will override the default values in the values.yaml.

**Comment by Syphixs** [comment]
yeah tried that already sadly the same error

**Comment by Syphixs** [comment]
oh you are right. 
Sadly the brokers and proxys second init containers will not start even with the new version.

**Comment by Syphixs** [comment]
fixed was not working cause I just had one pulsar bookie running
