### ISSUE TITLE
Decouple credentials from key secrets generation

### ISSUE THREAD

**Issue by nickelozz** [apache/pulsar-helm-chart#6]
**Is your feature request related to a problem? Please describe.**

As suggested here: https://pulsar.apache.org/docs/en/helm-deploy/#prepare-the-helm-release. The ```prepare_helm_release.sh``` script provided with this Helm chart can create a secret credentials resource and
> The username and password are used for logging into Grafana dashboard and Pulsar Manager.

However, I haven't been able to make use of such a feature for a number of reasons:

1. This secret doesn't seem to affect the ```pulsar-manager-deployment.yaml``` definition. Instead, the ```./templates/pulsar-manager-admin-secret.yaml``` seems to be the one providing the credentials for the pulsar manager (UI) (with the added possibility to overwrite via values.yaml at ```pulsar_manager.admin.user/password```).

2. Using the Pulsar chart as a dependency for an umbrella chart (this is currently my use case), will bring extra hassle that will make it very hard to have all resources follow the same naming structure, thus causing some resources to never be deployed successfully e.g.: ```./templates/grafana-deployment.yaml``` will complain that it couldn't find the secret created by the bash script. Attempting to fix this issue via the ```-k``` flag passed to the script will cause the JWT secret tokens to have a name that's unexpected by the broker, etc.

**Describe the solution you'd like**

The bash script should focus on the JWT secrets creation and nothing else.

The generation of user/password credentials for Grafana and Pulsar Manager should be delegated to individual secret resources that expose such credentials for overriding via ```values.yaml```. This provides flexibility in credentials usage/overwrite on a per-component basis.

Please advise.

**Comment by sijie** [comment]
@nickelozz good suggestions. I like the proposal. Are you interested in submitting a pull request for making the changes?

**Comment by nickelozz** [comment]
Apologies for the delay in replying.

I went ahead and created a [PR](https://github.com/apache/pulsar-helm-chart/pull/7) for this. Please take a look and let me know what you think.

**Comment by nickelozz** [comment]
@sijie any news on when this helm chart will be published in the official stable repo?

**Comment by sijie** [comment]
@nickelozz 

I will take a look. I don't think helm repo is accepting any new projects. we will submit it to the helm hub.
