### ISSUE TITLE
Helm chart dependencies do not follow best practices

### ISSUE THREAD

**Issue by Imunhatep** [apache/pulsar-helm-chart#65]
**Is your feature request related to a problem? Please describe.**
Charts do not follow common guideline: chart templates bring dependencies into the main chart instead of using [Helm dependency](https://helm.sh/docs/helm/helm_dependency/)

**Describe the solution you'd like**
Move services like prometheus, alert-manager, zookeeper  to a chart dependencies, That would simplified helm chart support and usage.

**Describe alternatives you've considered**
Do not see other options, cause the issue is that Chart structure is inconsistent and does not follow best practices

**Additional context**
As a chart reference with a lot of dependencies GitLab helm chart could be taken..

**Comment by chrisjohnson00** [comment]
+1
This would also fix the improper use of Prometheus as a deployment.  Prometheus needs to be a stateful set due to it's pvc.
