### ISSUE TITLE
Change Pulsar Manager  docker image version

### ISSUE THREAD

**Issue by dadacom379** [apache/pulsar-helm-chart#85]
When activating JWT token authentication the Pulsar manager is not connecting to broker. The manager image **v0.1.0** does not support JWT configuration.

- Docker image **v0.1.0** entrypoint: https://github.com/apache/pulsar-manager/blob/v0.1.0/docker/entrypoint.sh

In the new version **v0.2.0** the support is there:
- Docker image  entrypoint: https://github.com/apache/pulsar-manager/blob/v0.2.0/docker/entrypoint.sh

The solution is to change the docker version of the docker images from the helm chart.

The actual config in helm chart version **pulsar-2.6.2-1** : 
![image](https://user-images.githubusercontent.com/17455054/99808853-79a08980-2b0f-11eb-8611-154894869b48.png)

The correction should look like:
![image](https://user-images.githubusercontent.com/17455054/99809040-c08e7f00-2b0f-11eb-80eb-1622a00da46f.png)

**Comment by jeantil** [comment]
I found this issue while looking into #31 and #108 
Since the tag version is in values.yml you can use `--set images.pulsar_manager.tag=v0.2.0` to upgrade the version 
like so 
```
helm install --set images.pulsar_manager.tag=v0.2.0 --set initialize=true --set create_namespace=true --values examples/values-minikube.yaml --namespace pulsar pulsar-mini apache/pulsar
```
not sure if that will solve your issue but it's worth a shot

**Comment by lhotari** [comment]
The docker image version was upgraded as part of #206.
