### ISSUE TITLE
Please provide support for pulsar-sql in this helm chart

### ISSUE THREAD

**Issue by dhinesherode91** [apache/pulsar-helm-chart#89]
Currently, we cannot make use of pulsar-sql support when we deploy pulsar using this helm chart. It would be better to add pulsar-sql support in this official chart.

**Comment by DonHaul** [comment]
I am having the some troubles.
I found that kafkaesque has an image with [https://helm.kafkaesque.io](https://helm.kafkaesque.io) with pulsar SQL, I just might try that.

**Comment by eolivelli** [comment]
@DonHaul 
FYI the https://helm.kafkaesque.io chart has been mostly superseded by the new version
https://datastax.github.io/pulsar-helm-chart

**Comment by lhotari** [comment]
Closing this as outdated.
